spring:
  datasource:
    url: jdbc:mysql://192.168.0.21:3306/istory?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  jwt:
    issuer: user@gmail.com
    secret_key: study-springboot